import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Headless Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <header className="bg-white border-b sticky top-0 z-50 w-full">
          <div className="w-full lg:max-w-5xl mx-auto px-4 py-3 flex justify-between items-center">
            <div className="flex items-center space-x-2">
              <h1 className="text-2xl font-bold text-gray-800">Tech Blog</h1>
            </div>

            <nav className="hidden md:flex space-x-6">
              <a href="#" className="text-gray-700 hover:text-blue-600 transition flex items-center space-x-1">
                <span>Início</span>
              </a>
              <a href="#" className="text-gray-700 hover:text-blue-600 transition flex items-center space-x-1">
                <span>Artigos</span>
              </a>
              <a href="#" className="text-gray-700 hover:text-blue-600 transition flex items-center space-x-1">
                <span>Sobre</span>
              </a>
            </nav>

            <div className="flex items-center space-x-4">
              <button className="md:hidden">
              </button>
              <button>
              </button>
            </div>
          </div>
        </header>
        {children}
        <footer className="bg-gray-100 py-8">
        <div className="w-full lg:max-w-5xl mx-auto px-4 grid md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-lg font-semibold mb-4 text-gray-800">Sobre</h3>
            <p className="text-gray-600">Um blog pra quem deseja evoluir na programação. Conteúdo novo toda semana.</p>
          </div>

          <div className="col-start-3">
            <h3 className="text-lg font-semibold mb-4 text-gray-800">Newsletter</h3>
            <div className="flex">
              <input 
                type="email" 
                placeholder="Seu email" 
                className="w-full px-3 py-2 border rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <button className="bg-gray-600 text-white px-4 py-2 rounded-r-md hover:bg-gray-700 transition">
                Assinar
              </button>
            </div>
          </div>
        </div>

        <div className="text-center mt-8 pt-4 border-t border-gray-200 text-gray-600">
          © 2024 Tech Blog. Todos os direitos reservados.
        </div>
      </footer>
      </body>
    </html>
  );
}
